<h2>
    <?php 
        echo $this->object->Id == "" ? "<i class='fas fa-plus' style='font-size:24px'></i> " : "<i class='fas fa-edit' style='font-size:24px'></i> "; 
        echo $this->title; 
    ?> 
    <button id="cancelar" type="button" class="btn btn-outline-danger btn-sm">
        <i class='fas fa-angle-double-left'></i>
        Cancelar
    </button>
</h2>
<hr>
<form id="form" action="javascript:void(0);" enctype="multipart/form-data">
    <input name="Id" type="hidden" value="<?php echo $this->object->Id == '' ? '0' : $this->object->Id; ?>"/>
    <?php 
        foreach($this->object as $key => $value)	{
        if ($key!='Id') {
            $type = 'text';

            if ($this->is_Date($value)) {
                $type = 'date';
                $value = date('Y-m-d',strtotime($value));
            }
    ?>
    <div class="form-group row">
        <label for="input<?php echo $key;?>" class="col-sm-2 col-form-label"><?php echo $key;?></label>
        <div class="col-sm-6">
            <input type="<?php echo $type;?>" name="<?php echo $key;?>" value="<?php echo $value;?>" class="form-control" id="input<?php echo $key;?>">
        </div>
    </div>
    <?php
        }
    }?>
    <button type="submit" type="button" class="btn btn-outline-success"> 
        <i class='fas fa-save'></i>
        Guardar  
    </button>
</form>

<script>
$(document).ready(function(){
  $.getScript("lib/vcl/nav.js",function() {
    $("#form").submit(function(event) {
      show("<?php echo $this->controller; ?>","edit","#view",$(this).serialize());
    });
    $("#cancelar").click(function() {
      show("<?php echo $this->controller; ?>","index","#view","");
    });
  });
});
</script>
