<h2><?php echo $this->title; ?> 
    <button type="button" class="btn btn-outline-success btn-sm" id="nuevo">
        <i class='fas fa-plus'></i>
        Nuevo
    </button>
</h2>

<table class="table table-hover table-sm">
    <thead>
        <tr>
            <?php foreach($this->object as $key => $value) { if ($key!='Id') echo "<th>$key</th>"; } ?>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->objectList as $r): ?>
        <tr>
            <?php foreach($r as $key => $value)	{ if ($key!='Id') echo "<td>$value</td>"; } ?>
            <td> 
                <button class="btn btn-outline-primary btn-sm" id="edit<?php echo $r->Id; ?>">
                    <i class='fas fa-edit'></i>
                </button> 
            </td>
            <td> 
                <button class="btn btn-outline-danger btn-sm" id="delete<?php echo $r->Id; ?>">
                    <i class='fas fa-window-close'></i>
                </button> 
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<script>
	$(document).ready(function() {
		$.getScript("lib/vcl/nav.js", function() {
			$("#nuevo").click(function() {
				show("<?php echo $this->controller; ?>", "edit", "#view", "");
			});

			<?php foreach($this->objectList as $r): ?>
			$("#edit<?php echo $r->Id; ?>").click(function() {
				show("<?php echo $this->controller; ?>", "edit", "#view", "IdEdit=<?php echo $r->Id;?>");
			});

			$("#delete<?php echo $r->Id; ?>").click(function() {
				var deseaEliminar = confirm("¿Está seguro de eliminar?");

				if (deseaEliminar == true) {
					show("<?php echo $this->controller; ?>", "delete", "#view", "Id=<?php echo $r->Id; ?>");
				}
			});
			<?php endforeach; ?>
		});
	});
</script>