<div align="center">
	<a id="home">Home</a> | 
	<a id="formulario">Formulario</a> | 
	<a id="cargaCSV">Carga CSV</a> | 
	<a id="tabla">Mantenimiento</a> | 
	<a id="logout">Cerrar sesión</a>
</div>

<hr>

<div align="center">
    <div id="view" align="left" style="width: 70%;">
</div>

<script>
	$(document).ready(function() {
		$.getScript("lib/vcl/nav.js", function() {
			$("#home").click(function() {
				show("home", "index", "body", "");
			});
			$("#formulario").click(function() {
				show("formulario", "index", "#view", "");
			});
			$("#cargaCSV").click(function() {
				show("formulario", "cargarcsv", "#view", "");
			});
			$("#tabla").click(function() {
				show("usuario", "index", "#view", "");
			});
			$("#logout").click(function() { 
			    show("home","logout","body",""); 
			});
		});
	});
</script>