<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" >Titulo</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li> <a id="home">Home</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container body-content">
  <div id="view">
    <h1>Contenido Inicial</h1>
  </div>
  <hr>
  <footer>
    <p>
      &copy; <?php echo date("Y") ?> - Titulo
    </p>
  </footer>
</div>

<script>
$(document).ready(function(){
  $.getScript("lib/vcl/nav.js",function() {
    $("#home").click(function() { show("home","index","body",""); });
  });
});
</script>
