
<div class="container">
	<div class="row">
		<div class="col-md-4 col-sm-3 col-xs-1"></div>
		<div class="col-md-4 col-sm-6 col-xs-10" style="position: absolute; left: 50%; top: 50%; transform: translate(-50%, -50%);">
			<?php if ($this->getError() != '') { ?>
			<div class="alert alert-danger alert-dismissible fade show" role="alert"> 
			    <strong>Error!</strong> <?php echo $this->getError();?>
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"> 
				    <span aria-hidden="true">&times;</span>
				</button>
			</div>
			<?php } ?>
			<div class="card border-dark">
				<h5 class="card-header text-white" style="background-color: #343a40!important;">
                    <i class='fas fa-shield-alt'></i>
                    Acceso al sistema 
                </h5>
				<div class="card-body">
					<form id="form" action="javascript:void(0);" enctype="multipart/form-data">
						<div class="input-group input-group">
                          <div class="input-group-prepend">
                            <span class="input-group-text"><i class='fas fa-user-shield'></i></span>
                          </div>
							<input type="text" class="form-control" name="Usuario" placeholder="Ingresa tu usuario" />
						</div> 
						<br>
						<div class="input-group input-group">
                          <div class="input-group-prepend">
                            <span class="input-group-text"><i class='fas fa-key'></i></span>
                          </div>
							<input type="password" class="form-control" name="Password" placeholder="Ingresa tu contraseña" />
						</div>
						<br>
						<button type="submit" class="btn btn-success btn-block">
						    <strong>Ingresar</strong> <i class='fas fa-sign-in-alt'></i>
						</button>
					</form>
				</div>
			</div>
		</div>
		<div class="col-md-4 col-sm-3 col-xs-1"></div>
	</div>
</div>

<script>
	$(document).ready(function(){
	        $.getScript("lib/vcl/nav.js",function() {
	            $("#form").submit(function(event) {
	                show("home","setLogin","body",$(this).serialize());
	            });
	        });
	    });
</script>