<nav class="navbar navbar-expand-sm bg-light" style="height: 40px;">
    <div class="navbar-brand">
       <strong>Jugadores</strong>
    </div>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <button class="btn btn-success btn-sm" id="nuevo">
                    <i class='fas fa-user-plus'></i> Nuevo
                </button>
            </li>
        </ul>
    </div>
</nav>

<div class = "pt-2">
    <table class="table table-hover table-sm">
        <thead>
            <tr>
                <th>Código</th>
                <th>Año Nac</th>
                <th>1er Nombre</th>
                <th>1er Apellido</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php 
                foreach($this->object->getList() as $r): ?>
            <tr>
                <td><?php echo $r->Codigo?></td>
                <td><?php echo date('Y',strtotime($r->Fechanac)); ?></td>
                <td><?php echo $r->Nombre1?></td>
                <td><?php echo $r->Apellido1?></td>
                <td> 
                    <button class="btn btn-outline-primary btn-sm float-right" id="ver<?php echo $r->Id; ?>">
                        Ver <i class='far fa-address-card'></i>
                    </button> 
                </td>
            </tr>
            <?php endforeach; 
            ?>
        </tbody>
    </table>
</div>

<script>
	$(document).ready(function() {
		$.getScript("lib/vcl/nav.js", function() {
			$("#nuevo").click(function() {
				show("jugador", "abcjugador", "#view", "");
			});

			<?php foreach($this->object->getList() as $r): ?>
			$("#ver<?php echo $r->Id; ?>").click(function() {
				//show("jugador", "abcjugador", "#view", "IdEdit=<?php echo $r->Id;?>");
				show("jugador", "perfil", "#view", "IdEdit=<?php echo $r->Id;?>");
			});
			<?php endforeach; ?>
		});
	});
</script>