<!--
<h3> 
    <button type="button" class="btn btn-outline-primary btn-sm" id="regresar">
        <i class='fas fa-angle-double-left'></i>
    </button>
    <i class='fas fa-user'></i> Perfil
</h3>
-->

<nav class="navbar navbar-expand-sm bg-light" style="height: 40px;">
    <button type="button" class="btn btn-light btn-sm" id="regresar">
        <i class='fas fa-angle-double-left'></i>
    </button>
    <div class="navbar-brand">
        &nbsp <i class='fas fa-user'></i> <?php echo $this->object->Codigo; ?>
    </div>
    
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <button class="btn btn-warning btn-sm" id="editar">
                    <i class='fas fa-user-edit'></i> Editar
                </button>
            </li>
        </ul>
    </div>
</nav>

<div class="row pt-2"> 
    <div class="col-8 pr-2">
        <div class="card mb-3">
            <div class="row no-gutters">
                <div class="col-md-3">
                    <img src="<?php echo $this->object->Foto == "" ? "img/avatar.jpg" : $this->object->Foto;?>" class="img-thumbnail card-img" alt="Foto de perfil">
                </div>
                <div class="col-md-9">
                    <div class="card-body pt-0 pl-0 pr-0 pb-0">
                        <table class="table table-hover table-sm">
                            <tbody>
                                <tr>
                                    <th class="bg-primary text-white text-center">Año</th>
                                    <td class="text-center"> <?php echo date('Y',strtotime($this->object->Fechanac)); ?> </td>
                                </tr>
                                <tr>
                                    <th class="bg-primary text-white text-center">Nombre</th>
                                    <td class="text-center"> <?php echo $this->object->Nombre1." ".$this->object->Nombre2." ".$this->object->Apellido1." ".$this->object->Apellido2; ?> </td>
                                </tr>
                                <tr>
                                    <th class="bg-primary text-white text-center">Género</th>
                                    <td class="text-center"> <?php echo $this->getGenero($this->object->Genero); ?> </td>
                                </tr>
                                <tr>
                                    <th class="bg-primary text-white text-center">Altura y peso</th>
                                    <td class="text-center"> 120 cms / 95 lbs </td>
                                </tr>
                                <tr>
                                    <th class="bg-primary text-white text-center">Posición</th>
                                    <td class="text-center"> Delantero </td>
                                </tr>
                                <tr>
                                    <th class="bg-primary text-white text-center">Perfil</th>
                                    <td class="text-center"> Derecho </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="pt-0 pl-1 pr-1 pb-1">
                <span class="badge badge-primary"><i class='fas fa-baby'></i> 
                <?php 
                    echo $this->object->Fechanac; 
                    if ($this->object->Deptonac != '0' && $this->object->Deptonac != '') {
                        echo " ".$this->getMuni($this->object->Muninac); 
                        echo ", ".$this->getDepto($this->object->Deptonac);
                    }
                ?> 
                </span>
                
                <?php if ($this->object->Tiposangre != "0") { ?>
                <span class="badge badge-primary"><i class='fas fa-heart'></i> <?php echo $this->getTipoSangre($this->object->Tiposangre); ?> </span> 
                <?php }?>
                
                <?php if ($this->object->Escolaridad != "0") { ?>
                <span class="badge badge-primary"><i class='fas fa-user-graduate'></i> <?php echo $this->getEscolaridad($this->object->Escolaridad); ?> </span> 
                <?php }?>
                 
                <span class="badge badge-success"><i class='fas fa-phone'></i> <?php echo $this->object->Teljugador; ?> </span>
                
                <?php if ($this->object->Correo != "") { ?>
                <span class="badge badge-success"><i class='fas fa-envelope-open'></i> <?php echo $this->object->Correo; ?> </span> 
                <?php }?>
                
                <span class="badge badge-info"><i class='fas fa-address-card'></i> <?php echo $this->object->Cui; ?> </span>
                
                <?php if ($this->object->Nombrepadre != "") { ?>
                <span class="badge badge-success">
                    <i class='fas fa-male'></i> <?php echo $this->object->Nombrepadre; ?>
                    <?php if ($this->object->Telpadre != "") { ?>
                    <i class='fas fa-phone'></i> <?php echo $this->object->Telpadre; ?>
                    <?php }?>
                </span>
                <?php }?>
                
                <?php if ($this->object->Nombremadre != "") { ?>
                <span class="badge badge-success">
                    <i class='fas fa-female'></i> <?php echo $this->object->Nombremadre; ?> 
                    <?php if ($this->object->Telmadre != "") { ?>
                    <i class='fas fa-phone'></i> <?php echo $this->object->Telmadre; ?>
                    <?php }?>
                </span>
                <?php }?>
                
                <?php if ($this->object->Alergias != '') { ?>
                <span class="badge badge-warning"><i class='far fa-frown'></i> Alergias: <?php echo $this->object->Alergias; ?> </span>
                <?php } else {?>
                <span class="badge badge-success"><i class='far fa-grin-beam'></i> Sin alergias</span>
                <?php }?>
                
                <?php if ($this->object->Nit != "") { ?>
                <span class="badge badge-info"><i class='fas fa-id-badge'></i> NIT <?php echo $this->object->Nit; ?> </span>
                <?php }?>
                
                <?php if ($this->object->Pasaporte != "") { ?>
                <span class="badge badge-info">
                    <i class='fas fa-id-card'></i> PASS <?php echo $this->object->Pasaporte; ?> 
                    <?php if ($this->object->Pasaporteven != "") { ?>
                    <i class='fas fa-calendar-minus'></i> <?php echo $this->object->Pasaporteven; ?>
                    <?php }?>
                </span> 
                <?php }?>
                
                <?php if ($this->object->Visa != "") { ?>
                <span class="badge badge-info">
                    <i class='far fa-id-card'></i> VISA <?php echo $this->object->Visa; ?>
                    <?php if ($this->object->Visaven != "") { ?>
                    <i class='far fa-calendar-minus'></i> <?php echo $this->object->Visaven; ?>
                    <?php }?>
                </span>
                <?php }?>
                
                <?php if ($this->object->Visamex != "") { ?>
                <span class="badge badge-info">
                    <i class='far fa-id-card'></i> VISA MX <?php echo $this->object->Visamex; ?>
                    <?php if ($this->object->Visamexven != "") { ?>
                    <i class='far fa-calendar-minus'></i> <?php echo $this->object->Visamexven; ?>
                    <?php }?>
                </span>
                <?php }?>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-header bg-primary text-white">
                        Entrenos
                    </div>
                    <div class="card-body">
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <div class="card-header bg-primary text-white">
                        Partidos
                    </div>
                    <div class="card-body">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-4 pl-0">
        <div class="card border-primary">
            <div class="card-header bg-primary text-white pt-1 pb-1" >
                <strong>Evaluación individual</strong>
            </div>
            <div class="card-body pl-1 pr-1 pt-1 pb-1">
                <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100">20 METROS 80%</div>
                </div>
                <div class="progress mt-1">
                    <div class="progress-bar bg-success" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">ILLINOIS 100%</div>
                </div>
                <div class="progress mt-1">
                    <div class="progress-bar bg-info" role="progressbar" style="width: 70%" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100">GOLPEO 70%</div>
                </div>
                <div class="progress mt-1">
                    <div class="progress-bar bg-warning" role="progressbar" style="width: 60%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100">PASE 60%</div>
                </div>
                <div class="progress mt-1">
                    <div class="progress-bar bg-danger" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="60">CONDUCCION 50%</div>
                </div>
            </div>
        </div>
        <div class= "pt-2" style="width: 365px;">
            <div style="height:0px;" id="pos">
                <?php $this->posiciones(false); ?>
            </div>
            <img src="img/campo.jpg" class="img-thumbnail" alt="Foto de perfil">
            <button id="editpos" class="btn btn-outline-success btn-block" data-toggle="modal" data-target="#posiciones">
                <i class="fas fa-street-view" aria-hidden="true"></i>
                Editar posiciones
            </button>
        </div>
    </div>
</div>



<!-- MODAL PARA POSICIONES EN EL CAMPO DEL JUGADOR -->

<div class="modal fade" id="posiciones" tabindex="-1" aria-labelledby="Posiciones" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Posiciones de juego</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row">
                        <div class= "cod-lg-4" style="width: 365px;">
                            <div style="height:0px;" id="editposview"></div>
                            <img src="img/campo.jpg" class="img-thumbnail" alt="Foto del campo">
                        </div>
                        <div class="col-lg-7">
                            <form id="form" action="javascript:void(0);" enctype="multipart/form-data">
                                <input name="Id" type="hidden" value="<?php echo $this->object->Id; ?>"/>
                                <div class="row">
                                    <div class="col">
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input" id="A" name="A" <?php echo strpos($this->getPosicion(), "A") !== false ? "checked":""; ?>>
                                            <label class="custom-control-label" for="A">
                                                <span class="badge badge-success"><strong>EI</strong></span>
                                                Extremo izquierdo
                                            </label>
                                        </div>
                                        <br>
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input" id="B" name="B" <?php echo strpos($this->getPosicion(), "B") !== false ? "checked":""; ?>>
                                            <label class="custom-control-label" for="B">
                                                <span class="badge badge-success"><strong>ED</strong></span>
                                                Extremo Derecho
                                            </label>
                                        </div>
                                        <br>
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input" id="C" name="C" <?php echo strpos($this->getPosicion(), "C") !== false ? "checked":""; ?>>
                                            <label class="custom-control-label" for="C">
                                                <span class="badge badge-success"><strong>CD</strong></span>
                                                Centro Delantero
                                            </label>
                                        </div>
                                        <br>
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input" id="D" name="D" <?php echo strpos($this->getPosicion(), "D") !== false ? "checked":""; ?>>
                                            <label class="custom-control-label" for="D">
                                                <span class="badge badge-success"><strong>SD</strong></span>
                                                Segundo Delantero
                                            </label>
                                        </div>
                                        <br>
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input" id="E" name="E" <?php echo strpos($this->getPosicion(), "E") !== false ? "checked":""; ?>>
                                            <label class="custom-control-label" for="E">
                                                <span class="badge badge-success"><strong>MVI</strong></span>
                                                Volante Izquierdo
                                            </label>
                                        </div>
                                        <br>
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input" id="F" name="F" <?php echo strpos($this->getPosicion(), "F") !== false ? "checked":""; ?>>
                                            <label class="custom-control-label" for="F">
                                                <span class="badge badge-success"><strong>MVD</strong></span>
                                                Volante Derecho
                                            </label>
                                        </div>
                                        <br>
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input" id="G" name="G" <?php echo strpos($this->getPosicion(), "G") !== false ? "checked":""; ?>>
                                            <label class="custom-control-label" for="G">
                                                <span class="badge badge-success"><strong>MO</strong></span>
                                                Medio Ofensivo
                                            </label>
                                        </div>
                                        <br>
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input" id="H" name="H" <?php echo strpos($this->getPosicion(), "H") !== false ? "checked":""; ?>>
                                            <label class="custom-control-label" for="H">
                                                <span class="badge badge-info"><strong>MII</strong></span>
                                                Medio Interior Izquierdo
                                            </label>
                                        </div>
                                        <br>
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input" id="I" name="I" <?php echo strpos($this->getPosicion(), "I") !== false ? "checked":""; ?>>
                                            <label class="custom-control-label" for="I">
                                                <span class="badge badge-info"><strong>MID</strong></span>
                                                Medio Interior Derecho
                                            </label>
                                        </div>
                                        <br>
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input" id="J" name="J" <?php echo strpos($this->getPosicion(), "J") !== false ? "checked":""; ?>>
                                            <label class="custom-control-label" for="J">
                                                <span class="badge badge-danger"><strong>MCI</strong></span>
                                                Carrilero Izquierdo
                                            </label>
                                        </div>
                                        <br>
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input" id="K" name="K" <?php echo strpos($this->getPosicion(), "K") !== false ? "checked":""; ?>>
                                            <label class="custom-control-label" for="K">
                                                <span class="badge badge-danger"><strong>MCD</strong></span>
                                                Carrilero Derecho
                                            </label>
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input" id="L" name="L" <?php echo strpos($this->getPosicion(), "L") !== false ? "checked":""; ?>>
                                            <label class="custom-control-label" for="L">
                                                <span class="badge badge-warning"><strong>MMI</strong></span>
                                                Medio Mixto Izquierdo
                                            </label>
                                        </div>
                                        <br>
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input" id="M" name="M" <?php echo strpos($this->getPosicion(), "M") !== false ? "checked":""; ?>>
                                            <label class="custom-control-label" for="M">
                                                <span class="badge badge-warning"><strong>MMD</strong></span>
                                                Medio Mixto Derecho
                                            </label>
                                        </div>
                                        <br>
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input" id="N" name="N" <?php echo strpos($this->getPosicion(), "N") !== false ? "checked":""; ?>>
                                            <label class="custom-control-label" for="N">
                                                <span class="badge badge-warning"><strong>MC</strong></span>
                                                Medio de Contención
                                            </label>
                                        </div>
                                        <br>
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input" id="O" name="O" <?php echo strpos($this->getPosicion(), "O") !== false ? "checked":""; ?>>
                                            <label class="custom-control-label" for="O">
                                                <span class="badge badge-primary"><strong>DLI</strong></span>
                                                Lateral Izquierdo
                                            </label>
                                        </div>
                                        <br>
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input" id="P" name="P" <?php echo strpos($this->getPosicion(), "P") !== false ? "checked":""; ?>>
                                            <label class="custom-control-label" for="P">
                                                <span class="badge badge-primary"><strong>DLD</strong></span>
                                                Lateral Derecho
                                            </label>
                                        </div>
                                        <br>
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input" id="Q" name="Q" <?php echo strpos($this->getPosicion(), "Q") !== false ? "checked":""; ?>>
                                            <label class="custom-control-label" for="Q">
                                                <span class="badge badge-primary"><strong>DCI</strong></span>
                                                Defensa Central Izquierdo
                                            </label>
                                        </div>
                                        <br>
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input" id="R" name="R" <?php echo strpos($this->getPosicion(), "R") !== false ? "checked":""; ?>>
                                            <label class="custom-control-label" for="R">
                                                <span class="badge badge-primary"><strong>DCD</strong></span>
                                                Defensa Central Derecho
                                            </label>
                                        </div>
                                        <br>
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input" id="S" name="S" <?php echo strpos($this->getPosicion(), "S") !== false ? "checked":""; ?>>
                                            <label class="custom-control-label" for="S">
                                                <span class="badge badge-dark"><strong>DMI</strong></span>
                                                Defensa Marcador Izquierdo
                                            </label>
                                        </div>
                                        <br>
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input" id="T" name="T" <?php echo strpos($this->getPosicion(), "T") !== false ? "checked":""; ?>>
                                            <label class="custom-control-label" for="T">
                                                <span class="badge badge-dark"><strong>DMD</strong></span>
                                                Defensa Marcador Derecho
                                            </label>
                                        </div>
                                        <br>
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input" id="U" name="U" <?php echo strpos($this->getPosicion(), "U") !== false ? "checked":""; ?>>
                                            <label class="custom-control-label" for="U">
                                                <span class="badge badge-dark"><strong>DMC</strong></span>
                                                Defensa Marcador Central
                                            </label>
                                        </div>
                                        <br>
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input" id="V" name="V" <?php echo strpos($this->getPosicion(), "V") !== false ? "checked":""; ?>>
                                            <label class="custom-control-label" for="V">
                                                <span class="badge badge-dark"><strong>P</strong></span>
                                                Portero
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal" id="savepos">Guardar</button>
            </div>
        </div>
    </div>
</div>

<script>
	$(document).ready(function() {
		$.getScript("lib/vcl/nav.js", function() {
			$("#regresar").click(function() {
				show("jugador", "index", "#view", "");
			});
			$("#savepos").click(function() {
				show("jugador", "savePosition", "#pos", $("form").serialize());
			});
			$("#editar").click(function() {
				show("jugador", "abcjugador", "#view", "IdEdit=<?php echo $this->object->Id; ?>");
			});
			$("#editpos").click(function() {
				show("jugador", "posiciones", "#editposview", "IdEdit=<?php echo $this->object->Id; ?>");
			});
			$("#A").click(function() {
				show("jugador", "posiciones", "#editposview", $("form").serialize());
			});
			$("#B").click(function() {
				show("jugador", "posiciones", "#editposview", $("form").serialize());
			});
			$("#C").click(function() {
				show("jugador", "posiciones", "#editposview", $("form").serialize());
			});
			$("#D").click(function() {
				show("jugador", "posiciones", "#editposview", $("form").serialize());
			});
			$("#E").click(function() {
				show("jugador", "posiciones", "#editposview", $("form").serialize());
			});
			$("#F").click(function() {
				show("jugador", "posiciones", "#editposview", $("form").serialize());
			});
			$("#G").click(function() {
				show("jugador", "posiciones", "#editposview", $("form").serialize());
			});
			$("#H").click(function() {
				show("jugador", "posiciones", "#editposview", $("form").serialize());
			});
			$("#I").click(function() {
				show("jugador", "posiciones", "#editposview", $("form").serialize());
			});
			$("#J").click(function() {
				show("jugador", "posiciones", "#editposview", $("form").serialize());
			});
			$("#K").click(function() {
				show("jugador", "posiciones", "#editposview", $("form").serialize());
			});
			$("#L").click(function() {
				show("jugador", "posiciones", "#editposview", $("form").serialize());
			});
			$("#M").click(function() {
				show("jugador", "posiciones", "#editposview", $("form").serialize());
			});
			$("#N").click(function() {
				show("jugador", "posiciones", "#editposview", $("form").serialize());
			});
			$("#O").click(function() {
				show("jugador", "posiciones", "#editposview", $("form").serialize());
			});
			$("#P").click(function() {
				show("jugador", "posiciones", "#editposview", $("form").serialize());
			});
			$("#Q").click(function() {
				show("jugador", "posiciones", "#editposview", $("form").serialize());
			});
			$("#R").click(function() {
				show("jugador", "posiciones", "#editposview", $("form").serialize());
			});
			$("#S").click(function() {
				show("jugador", "posiciones", "#editposview", $("form").serialize());
			});
			$("#T").click(function() {
				show("jugador", "posiciones", "#editposview", $("form").serialize());
			});
			$("#U").click(function() {
				show("jugador", "posiciones", "#editposview", $("form").serialize());
			});
			$("#V").click(function() {
				show("jugador", "posiciones", "#editposview", $("form").serialize());
			});
		});
	});
</script>