<?php 
if (strpos($this->getPosicion(), "A") !== false) { ?>
<!-- [A] EI - EXTREMO IZQUIERDO -->
<div style="position: relative; top: 70px; left: 50px; width: 75px; height:0px"> 
    <span class="badge badge-pill badge-success" data-toggle="tooltip" data-placement="top" title="Extremo Izquierdo"><i class="fas fa-user-alt" aria-hidden="true"></i></span>
    <span class="badge badge-light"><strong>EI</strong></span>
</div>
<?php } 

if (strpos($this->getPosicion(), "B") !== false) { ?>
<!-- [B] ED - EXTREMO DERECHO -->
<div style="position: relative; top: 70px; left: 265px; width: 75px; height:0px"> 
    <span class="badge badge-light"><strong>ED</strong></span>
    <span class="badge badge-pill badge-success"><i class="fas fa-user-alt" aria-hidden="true"></i></span>
</div>
<?php } 

if (strpos($this->getPosicion(), "C") !== false) { ?>
<!-- [C] CD - CENTRO DELANTERO -->
<div style="position: relative; top: 55px; left: 125px; width: 75px; height:0px"> 
    <span class="badge badge-pill badge-success"><i class="fas fa-user-alt" aria-hidden="true"></i></span>
    <span class="badge badge-light"><strong>CD</strong></span>
</div>
<?php } 

if (strpos($this->getPosicion(), "D") !== false) { ?>
<!-- [D] SD - SEGUNDO DELANTERO -->
<div style="position: relative; top: 90px; left: 190px; width: 75px; height:0px"> 
    <span class="badge badge-pill badge-success"><i class="fas fa-user-alt" aria-hidden="true"></i></span>
    <span class="badge badge-light"><strong>SD</strong></span>
</div>
<?php } 

if (strpos($this->getPosicion(), "E") !== false) { ?>
<!-- [E] MVI - VOLANTE IZQUIERDO -->
<div style="position: relative; top: 135px; left: 50px; width: 75px; height:0px"> 
    <span class="badge badge-pill badge-success"><i class="fas fa-user-alt" aria-hidden="true"></i></span>
    <span class="badge badge-light"><strong>MVI</strong></span>
</div>
<?php } 

if (strpos($this->getPosicion(), "F") !== false) { ?>
<!-- [F] MVD - MEDIO DERECHO -->
<div style="position: relative; top: 135px; left: 250px; width: 75px; height:0px">
    <span class="badge badge-light"><strong>MVD</strong></span>
    <span class="badge badge-pill badge-success"><i class="fas fa-user-alt" aria-hidden="true"></i></span>
</div>
<?php } 

if (strpos($this->getPosicion(), "G") !== false) { ?>
<!-- [G] MO - MEDIO OFENSIVO -->
<div style="position: relative; top: 145px; left: 170px; width: 75px; height:0px"> 
    <span class="badge badge-pill badge-success"><i class="fas fa-user-alt" aria-hidden="true"></i></span>
    <span class="badge badge-light"><strong>MO</strong></span>
</div>
<?php } 

if (strpos($this->getPosicion(), "H") !== false) { ?>
<!-- [H] MII - MEDIO INFERIOR IZQUIERDO -->
<div style="position: relative; top: 195px; left: 105px; width: 75px; height:0px">
    <span class="badge badge-light"><strong>MII</strong></span>
    <span class="badge badge-pill badge-info"><i class="fas fa-user-alt" aria-hidden="true"></i></span>
</div>
<?php } 

if (strpos($this->getPosicion(), "I") !== false) { ?>
<!-- [I] MID - MEDIO INFERIOR DERECHO -->
<div style="position: relative; top: 195px; left: 205px; width: 75px; height:0px">
    <span class="badge badge-pill badge-info"><i class="fas fa-user-alt" aria-hidden="true"></i></span>
    <span class="badge badge-light"><strong>MID</strong></span>
</div>
<?php } 

if (strpos($this->getPosicion(), "J") !== false) { ?>
<!-- [J] MCI - CARRILERO IZQUIERDO -->
<div style="position: relative; top: 225px; left: 40px; width: 75px; height:0px"> 
    <span class="badge badge-pill badge-danger"><i class="fas fa-user-alt" aria-hidden="true"></i></span>
    <span class="badge badge-light"><strong>MCI</strong></span>
</div>
<?php } 

if (strpos($this->getPosicion(), "K") !== false) { ?>
<!-- [K] MCD - CARRILERO DERECHO -->
<div style="position: relative; top: 225px; left: 260px; width: 75px; height:0px">
    <span class="badge badge-light"><strong>MCD</strong></span>
    <span class="badge badge-pill badge-danger"><i class="fas fa-user-alt" aria-hidden="true"></i></span>
</div>
<?php } 

if (strpos($this->getPosicion(), "L") !== false) { ?>
<!-- [L] MMI - MEDIO MIXTO IZQUIERDO -->
<div style="position: relative; top: 260px; left: 70px; width: 75px; height:0px"> 
    <span class="badge badge-light"><strong>MMI</strong></span>
    <span class="badge badge-pill badge-warning"><i class="fas fa-user-alt" aria-hidden="true"></i></span>
</div>
<?php } 

if (strpos($this->getPosicion(), "M") !== false) { ?>
<!-- [M] MMD - MEDIO MIXTO DERECHO -->
<div style="position: relative; top: 260px; left: 230px; width: 75px; height:0px"> 
    <span class="badge badge-pill badge-warning"><i class="fas fa-user-alt" aria-hidden="true"></i></span>
    <span class="badge badge-light"><strong>MMD</strong></span>
</div>
<?php } 

if (strpos($this->getPosicion(), "N") !== false) { ?>
<!-- [N] MC - MEDIO DE CONTENSION -->
<div style="position: relative; top: 285px; left: 170px; width: 75px; height:0px"> 
    <span class="badge badge-pill badge-warning"><i class="fas fa-user-alt" aria-hidden="true"></i></span>
    <span class="badge badge-light"><strong>MC</strong></span>
</div>
<?php } 

if (strpos($this->getPosicion(), "O") !== false) { ?>
<!-- [O] DLI - LATERAL IZQUIERDO -->
<div style="position: relative; top: 315px; left: 45px; width: 75px; height:0px"> 
    <span class="badge badge-pill badge-primary"><i class="fas fa-user-alt" aria-hidden="true"></i></span>
    <span class="badge badge-light"><strong>DLI</strong></span>
</div>
<?php } 

if (strpos($this->getPosicion(), "P") !== false) { ?>
<!-- [P] DLD - LATERAL DERECHO -->
<div style="position: relative; top: 315px; left: 258px; width: 75px; height:0px">
    <span class="badge badge-light"><strong>DLD</strong></span>
    <span class="badge badge-pill badge-primary"><i class="fas fa-user-alt" aria-hidden="true"></i></span>
</div>
<?php } 

if (strpos($this->getPosicion(), "Q") !== false) { ?>
<!-- [Q] DCI - DEFENSA CENTRAL IZQUIERDO -->
<div style="position: relative; top: 330px; left: 120px; width: 75px; height:0px"> 
    <span class="badge badge-pill badge-primary"><i class="fas fa-user-alt" aria-hidden="true"></i></span>
    <span class="badge badge-light"><strong>DCI</strong></span>
</div>
<?php } 

if (strpos($this->getPosicion(), "R") !== false) { ?>
<!-- [R] DCD - DEFENSA CENTRAL DERECHO -->
<div style="position: relative; top: 330px; left: 185px; width: 75px; height:0px">
    <span class="badge badge-light"><strong>DCD</strong></span>
    <span class="badge badge-pill badge-primary"><i class="fas fa-user-alt" aria-hidden="true"></i></span>
</div>
<?php } 

if (strpos($this->getPosicion(), "S") !== false) { ?>
<!-- [S] DMI - DEFENSA MARCADOR IZQUIERDO -->
<div style="position: relative; top: 375px; left: 55px; width: 75px; height:0px">
    <span class="badge badge-light"><strong>DMI</strong></span>
    <span class="badge badge-pill badge-dark"><i class="fas fa-user-alt" aria-hidden="true"></i></span>
</div>
<?php } 

if (strpos($this->getPosicion(), "T") !== false) { ?>
<!-- [T] DMD - DEFENSA MARCADOR DERECHO -->
<div style="position: relative; top: 375px; left: 247px; width: 75px; height:0px">
    <span class="badge badge-pill badge-dark"><i class="fas fa-user-alt" aria-hidden="true"></i></span>
    <span class="badge badge-light"><strong>DMD</strong></span>
</div>
<?php } 

if (strpos($this->getPosicion(), "U") !== false) { ?>
<!-- [U] DMC - DEFENSA MARCADOR CENTRAL -->
<div style="position: relative; top: 390px; left: 170px; width: 75px; height:0px">
    <span class="badge badge-pill badge-dark"><i class="fas fa-user-alt" aria-hidden="true"></i></span>
    <span class="badge badge-light"><strong>DMC</strong></span>
            </div>
<?php } 

if (strpos($this->getPosicion(), "V") !== false) { ?>
<!-- [V] P - PORTERO -->
<div style="position: relative; top: 450px; left: 170px; width: 75px; height:0px">
    <span class="badge badge-pill badge-dark"><i class="fas fa-user-alt" aria-hidden="true"></i></span>
    <span class="badge badge-light"><strong>P</strong></span>
</div>
<?php } ?>