<h1>Carga de archivo CSV</h1>

<form action= "vie/formulario/csv.php" method="post">
    1. <button type="submit" id="descargar">Descargar CSV</button>
</form>
<br>
<form id="form" action="javascript:void(0);" enctype="multipart/form-data">
    2. <input id="file_csv" name='file' type="file"> <br> <br>
    3. <button type="submit">Cargar CSV</button>
</form>
<br>
<div id="csv"></div>

<script>
$(document).ready(function() {
    $.getScript("lib/vcl/nav.js",function() {
        $("#form").submit(function(event) {
            var form = $('#form')[0];
            var formData = new FormData(form);
            var file_csv = $("#file_csv")[0];
            formData.append(file_csv.name, file_csv.files[0]);
            loadCSV("formulario","mostrarcsv","#csv",formData);
        });
    });
});
</script>