<h2>Cargar CSV</h2>

<hr>

<div class="row">
    <div class="col-3 col-sm-3 col-md-2 col-lg-2">
        <form action= "vie/formulario/csv.php" method="post">
            <button type="submit" id="descargar" type="button" class="btn btn-outline-primary btn-block">
                <i class='fas fa-download'></i> CSV
            </button>
        </form>
    </div>
    <div class="col-9 col-sm-9 col-md-10 col-lg-10">
        <form id="form" action="javascript:void(0);" enctype="multipart/form-data">
            <div class="input-group ">
                <div class="custom-file">
                    <input type="file" name='file' class="custom-file-input" id="file_csv" required>
                    <label class="custom-file-label" for="file_csv">Buscar CSV descargado...</label>
                </div>
                <div class="input-group-append">
                    <button class="btn btn-outline-success" type="submit">
                        <i class='fas fa-upload'></i> CSV
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

<br>

<div id="csv"></div>

<script>
$(document).ready(function() {
    $.getScript("lib/vcl/nav.js",function() {
        $("#form").submit(function(event) {
            var form = $('#form')[0];
            var formData = new FormData(form);
            var file_csv = $("#file_csv")[0];
            formData.append(file_csv.name, file_csv.files[0]);
            loadCSV("formulario","mostrarcsv","#csv",formData);
        });
    });
});

$(".custom-file-input").on("change", function() {
    var fileName = $(this).val().split("\\").pop();
    $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
});
</script>