<nav class="navbar navbar-expand-sm bg-light" style="height: 40px;">
    <div class="navbar-brand">
       <i class='fas fa-users'></i> <strong>Selecciones para el Mundial </strong>
    </div>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <select id="Mundial" name="Mundial" class="form-control">
                    <?php for ($a = 2021; $a < (date('Y')+10); $a++) { ?>
                        <option value="<?php echo $a; ?>" <?php echo $a==(date('Y')+1) ? 'selected' : ''; ?>><?php echo $a; ?></option>
                    <?php } ?>
                </select>
            </li>
        </ul>
    </div>
</nav>

<div class = "pt-2" id="sel">
    <?php $this->selecciones(); ?>
</div>

<script>
	$(document).ready(function() {
		$.getScript("lib/vcl/nav.js", function() {
			$("#Mundial").change(function() { 
                show("seleccion","selecciones","#sel","Mundial="+$("#Mundial").val()); 
            });
			<?php foreach($this->object->getList() as $r): ?>
			$("#editar<?php echo $r->Id; ?>").click(function() {
				show("seleccion", "abc", "#view", "IdEdit=<?php echo $r->Id;?>");
			});
			<?php endforeach; ?>
		});
	});
</script>